[manifest]
version = "1"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''table.sort(loadBeatQueue,function(k1, k2)'''
position = "before"
payload = '''
cs.fsrBeat = nil
cs.progessBarStartOffset = 8

for _, event in ipairs(cs.playEvents) do
    if event.type == "showResults" then
        cs.fsrBeat = event.time + cs.progessBarStartOffset
        break
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''function GameManager:drawExpandedHud()'''
position = "after"
payload = '''
if mods.lemontweaks.config.chartprog.useVFXcolor then
    color(cs.vfx.uiColor)
else
    color(1)
end

if cs.fsrBeat ~= nil then
    cs.barWidth = nil
    cs.barXpos = nil

    if mods.lemontweaks.config.chartprog.reverseDirection then 
        cs.barWidth = math.min(math.max(project.res.x * (1 - ((cs.cBeat + cs.progessBarStartOffset) / cs.fsrBeat)), 0), project.res.x)
    else
        cs.barWidth = math.min(math.max(project.res.x * ((cs.cBeat + cs.progessBarStartOffset) / cs.fsrBeat), 0), project.res.x)
    end

    if mods.lemontweaks.config.chartprog.centerBar then
        cs.barXpos = (project.res.x - cs.barWidth) / 2
    else
        cs.barXpos = 0
    end

    if not mods.lemontweaks.config.chartprog.useVFXcolor then
        if mods.lemontweaks.config.chartprog.topBar then
            love.graphics.rectangle('fill', cs.barXpos - 1, -1, cs.barWidth + 2, mods.lemontweaks.config.chartprog.barHeight + 2)
        end

        if mods.lemontweaks.config.chartprog.bottomBar then
            love.graphics.rectangle('fill', cs.barXpos - 1, project.res.y - mods.lemontweaks.config.chartprog.barHeight - 1, cs.barWidth + 2, mods.lemontweaks.config.chartprog.barHeight + 2)
        end

        color(0)
    end

    if mods.lemontweaks.config.chartprog.topBar then
        love.graphics.rectangle('fill', cs.barXpos, 0, cs.barWidth, mods.lemontweaks.config.chartprog.barHeight)
    end

    if mods.lemontweaks.config.chartprog.bottomBar then
        love.graphics.rectangle('fill', cs.barXpos, project.res.y - mods.lemontweaks.config.chartprog.barHeight, cs.barWidth, mods.lemontweaks.config.chartprog.barHeight)
    end

    local percent

    if mods.lemontweaks.config.chartprog.showDecimalPercentage then
        percent = string.format("%.2f", math.min(math.max(100 * ((cs.cBeat + cs.progessBarStartOffset) / cs.fsrBeat), 0), 100))
    else
        percent = math.floor(math.min(math.max(100 * ((cs.cBeat + cs.progessBarStartOffset) / cs.fsrBeat), 0), 100))
    end

    love.graphics.setFont(fonts.digitalDisco)

    if mods.lemontweaks.config.chartprog.showPercentage then
        love.graphics.print(percent .. "%", 3, mods.lemontweaks.config.chartprog.barHeight + 3)
    end
end
'''
match_indent = true
