[manifest]
version = "1.0.0"
dump_lua = true
priority = 0



# block

[[patches]]
[patches.pattern]
target = "obj/notes/Block.lua"
pattern = '''self.hitSound = sounds.click'''
position = "at"
payload = '''
self.hitSound = sounds.block
'''
match_indent = true



# side

[[patches]]
[patches.pattern]
target = "obj/notes/Side.lua"
pattern = '''--self.hitSound = sounds.side'''
position = "at"
payload = '''self.hitSound = sounds.side'''
match_indent = true



# miss

[[patches]]
[patches.pattern]
target = "obj/GameManager.lua"
pattern = '''
te.playOne(sounds.mine,"static",'sfx')
'''
position = "at"
payload = '''
-- this doesn't seem to do anything, but i'm leaving it here
te.playOne(sounds.miss,"static",'sfx')
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/notes/Block.lua"
pattern = '''
te.playOne(sounds.mine,"static",'sfx',math.min(1,cs.noteVolume))
'''
position = "at"
payload = '''
if self.name == "mine" or self.name == "mineHold" then
    te.playOne(sounds.mine,"static",'sfx',math.min(1,cs.noteVolume))
else
    te.playOne(sounds.miss,"static",'sfx',math.min(1,cs.noteVolume))
end
'''
match_indent = true



# hover

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Game.lua"
pattern = '''
te.playOne(sounds.click,"static",'sfx',1, 0.5)
'''
position = "at"
payload = '''
te.playOne(sounds.hover,"static",'sfx',1, 0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/MarathonResults.lua"
pattern = '''
te.play(sounds.click, "static", "sfx", 0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover, "static", "sfx", 0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/OptionsList.lua"
pattern = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/RadialList.lua"
pattern = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/SortingButton.lua"
pattern = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Costumes.lua"
pattern = '''
te.play(sounds.click, "static", "sfx", 0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover, "static", "sfx", 0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Keybinds.lua"
pattern = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.hover,"static",'sfx',0.5)
'''
match_indent = true



# click

[[patches]]
[patches.pattern]
target = "obj/OptionsList.lua"
pattern = '''
te.play(sounds.hold,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "obj/RadialList.lua"
pattern = '''
te.play(sounds.hold,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Costumes.lua"
pattern = '''
te.play(sounds.hold, "static", "sfx", 0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Keybinds.lua"
pattern = '''
te.play(sounds.hold,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Menu.lua"
pattern = '''
te.play(sounds.hold,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/SongSelect.lua"
pattern = '''
te.play(sounds.hold,"static",'sfx',0.5)
'''
position = "at"
payload = '''
te.play(sounds.click,"static",'sfx',0.5)
'''
match_indent = true



# caution

[[patches]]
[patches.pattern]
target = "states/EditorWarning.lua"
pattern = '''
st:setInit(function(self)
	self.caution = ez.newjson('assets/editor/warning/caution'):instance()
	shuv.resetPal()
	shuv.pal[2] = {r=255,g=216,b=0}
	te.play('assets/music/caution.ogg','stream','music')
end)
'''
position = "at"
payload = '''
-- same with this

st:setInit(function(self)
    audioPath = 'assets/music/caution.ogg'

    if mods.lemontweaks.config.customsounds.music.caution ~= "default" and love.filesystem.exists("Mods/lemontweaks/customsounds/music/caution/" .. mods.lemontweaks.config.customsounds.music.caution) then
        audioPath = "Mods/lemontweaks/customsounds/music/caution/" .. mods.lemontweaks.config.customsounds.music.caution
    end

	self.caution = ez.newjson('assets/editor/warning/caution'):instance()
	shuv.resetPal()
	shuv.pal[2] = {r=255,g=216,b=0}
	te.play(audioPath,'stream','music')
end)
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "states/Error.lua"
pattern = '''
st:setInit(function(self)
	self.errorMessage = self.errorMessage or 'No error provided???'
	log('In-level error screen!','error')
	log(self.errorMessage,'error')
	self.errorSprite = ez.newjson('assets/error/error'):instance()
	shuv.resetPal()
	te.play('assets/music/caution.ogg','stream','music')
end)
'''
position = "at"
payload = '''
-- mrow :3

st:setInit(function(self)
    audioPath = 'assets/music/caution.ogg'

    if mods.lemontweaks.config.customsounds.music.caution ~= "default" and love.filesystem.exists("Mods/lemontweaks/customsounds/music/caution/" .. mods.lemontweaks.config.customsounds.music.caution) then
        audioPath = "Mods/lemontweaks/customsounds/music/caution/" .. mods.lemontweaks.config.customsounds.music.caution
    end

	self.errorMessage = self.errorMessage or 'No error provided???'
	log('In-level error screen!','error')
	log(self.errorMessage,'error')
	self.errorSprite = ez.newjson('assets/error/error'):instance()
	shuv.resetPal()
	te.play(audioPath,'stream','music')
end)
'''
match_indent = true



# menu loop

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''if savedata.options.audio.musicvolume/10 ~= self.baseVolume then'''
payload = '''
if self.music and self.music.source and mods.lemontweaks.config.customsounds.music.useCustomPlayer then
	local time = self.music.source:tell()
	local duration = self.music.source:getDuration()

	if time + 0.5 >= duration then
		print("song ended")
		self:stop()
		self:play()
	end
end

'''
position = "before"
target = "obj/MenuMusicManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''function MenuMusicManager:forceUnmute()'''
payload = '''
	if lemontweaks.menuPlaying or not mods.lemontweaks.config.customsounds.music.useCustomPlayer then
		-- nothing
	else
		self.menuMusicManager:forceMute()
		self.menuMusicManager:seek(lemontweaks.menuloopInfo.playhead)
		return
	end
'''
position = "after"
target = "obj/MenuMusicManager.lua"

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
function MenuMusicManager:play()
	if savedata.options.audio.playMenuMusic then
		self.music
			:load('assets/music/menuloop.ogg')
			:setBPM(108)
			:setLooping(true)
			:play()
	end
end
'''
payload = '''

-- Penta: Since were doing stupid stuff in here already, lets just initialize all of the lemontweaks customplayer here

lemontweaks = lemontweaks or {}
lemontweaks.nativefs = lemontweaks.nativefs or require("Mods.lemontweaks.dependencies.nativefs")
lemontweaks.menuOpen = lemontweaks.menuOpen or false
lemontweaks.mouseWasDown = lemontweaks.mouseWasDown or false
lemontweaks.moveMenu = lemontweaks.moveMenu or false
lemontweaks.tempDontAdvance = lemontweaks.tempDontAdvance or false
lemontweaks.current = lemontweaks.current or 0
lemontweaks.levellist = lemontweaks.levellist or {}

-- me: *not knowing what to do*
-- some random roblox forum: i gotchu bbg
function lemontweaks.shuffle(array)
	local deck = array

	for i = #deck, 2, -1 do -- Start from the last card down to the second card
		local j = math.random(1, i)  -- Select a random index between 1 and i
		deck[i], deck[j] = deck[j], deck[i]  -- Swap the randomly selected card with the current card
		deck[i].index = i
		deck[j].index = j
	end

	return deck
end
lemontweaks.helperOutlineRect = function(x, y, w, h)
    color(1)
    love.graphics.rectangle('fill', x - 1, y - 1, w + 2, h + 2)
    color(0)
    love.graphics.rectangle('fill', x, y, w, h)
end
lemontweaks.helperImgButton = function(sprite, x, y, run, mouseJustPressed)
    love.graphics.draw(sprite, x, y)

    local w = sprite:getWidth()
    local h = sprite:getHeight()

    local mx = mouse.rx
    local my = mouse.ry

    if mouseJustPressed then
        if mx >= x and mx <= x + w and my >= y and my <= y + h then
            run()
        end
    end
end
local function getAllLevels()
    local levels = {}
    local workshopPath = love.filesystem.getRealDirectory("Workshop/");

	if lemontweaks.didINIT then
		print("mod has init")
	else
		print("mod has not init")
	end

    local folders = lemontweaks.nativefs.getDirectoryItems(workshopPath)

    for _, folder in ipairs(folders) do

        local levelPath = workshopPath .. "/" .. folder

        if lemontweaks.nativefs.getInfo(levelPath .. "/level.json") then
            local levelDat = json.decode(lemontweaks.nativefs.read(levelPath .. "/level.json"))
            local manifestDat

            if lemontweaks.nativefs.getInfo(levelPath .. "/manifest.json")  then
                manifestDat = json.decode(lemontweaks.nativefs.read(levelPath .. "/manifest.json"))
            else
                -- old level fix
                manifestDat = levelDat
            end

            local playEvent

            for _, event in ipairs(levelDat.events) do
                if event.type == "play" then
                    playEvent = event
                    break
                end
            end

			if playEvent == nil then
				print("no play event found, skipped.")
			else
				table.insert(levels, {
					name = manifestDat.metadata.songName,
					artist = manifestDat.metadata.artist,
					bpm = playEvent.bpm,
					file = workshopPath .. "/" .. folder .. "/" .. playEvent.file,
					offset = playEvent.offset or 0
				})
			end
        end
    end

    return levels
end

local fetchedLevels = getAllLevels()
table.sort(fetchedLevels, function(a, b)
	return (a.artist or "unknown"):gsub("%b[]", "") .. " - " .. (a.name or "unknown"):gsub("%b[]", "") < (b.artist or "unknown"):gsub("%b[]", "") .. " - " .. (b.name or "unknown"):gsub("%b[]", "")
end)
for i, data in ipairs(fetchedLevels) do lemontweaks.levellist[i] = data end
lemontweaks.fetchedLevels = lemontweaks.shuffle(fetchedLevels)

math.randomseed(love.timer.getTime() * 100000)
fonts.digitalDiscoBold = fonts.digitalDiscoBold or love.graphics.newFont("Mods/lemontweaks/assets/fonts/DigitalDisco.ttf", 16)

-- initializing end

function MenuMusicManager:play()
	if not mods.lemontweaks.config.customsounds.music.repeatSameSong and not lemontweaks.tempDontAdvance then
		lemontweaks.current = lemontweaks.current + 1
	end
	lemontweaks.tempDontAdvance = false

	if lemontweaks.current > #lemontweaks.fetchedLevels then
		lemontweaks.current = 1
	end

	if lemontweaks.current < 1 then
        lemontweaks.current = #lemontweaks.fetchedLevels
    end

	lemontweaks.menuX = lemontweaks.menuOpen and -(fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 11 + playerIconPadding * 4) or 0

	if savedata.options.audio.playMenuMusic then
        local audioPath = 'assets/music/menuloop.ogg'
		local loop = true
		local bpm = mods.lemontweaks.config.customsounds.music.menuloopBPM
		local songOffset = mods.lemontweaks.config.customsounds.music.menuloopOffset

        if mods.lemontweaks.config.customsounds.music.menuloop ~= "default"
        and love.filesystem.getInfo("Mods/lemontweaks/customsounds/music/menuloop/" ..
            mods.lemontweaks.config.customsounds.music.menuloop) then

            audioPath = "Mods/lemontweaks/customsounds/music/menuloop/" .. mods.lemontweaks.config.customsounds.music.menuloop
        end

		if mods.lemontweaks.config.customsounds.music.useCustomPlayer then
			print(json.encode(lemontweaks.fetchedLevels[lemontweaks.current]))
            audioPath = lemontweaks.fetchedLevels[lemontweaks.current].file
			loop = false
            bpm = lemontweaks.fetchedLevels[lemontweaks.current].bpm
            offset = lemontweaks.fetchedLevels[lemontweaks.current].offset * 1000
		end

        if audioPath:match("^%a:[/\\]") then
            local fileData, error = lemontweaks.nativefs.newFileData(audioPath)
            if not fileData then
                error("Failed to load audio: " .. tostring(error))
            end

            self.music:load(fileData)
        else
            self.music:load(audioPath)
        end

		self.music
			:setBPM(bpm)
			:setLooping(loop)
			:play()

        local offset = songOffset / 1000

        if offset >= 0 then
            self.music.source:seek(offset)
        end

        self.music:setTime(offset)
	end
end

function MenuMusicManager:getInfo()
	if self.music and self.music.source then
    	return { playhead = self.music.source:tell("seconds"), volume = self.music.source:getVolume() }
	end

	return { playhead = 0, volume = 0 }
end

function MenuMusicManager:seek(time)
	if self.music and self.music.source then
		self.music.source:seek(time)
	end
end
'''
position = "at"
target = "obj/MenuMusicManager.lua"
