[manifest]
version = "1.0.0"
dump_lua = true
priority = 1



# custom player menu

[[patches]]
[patches.pattern]
match_indent = true
pattern = '''
color('black')
love.graphics.print(version, project.res.cx * 2 - fonts.digitalDisco:getWidth(version) - 10 ,6 + self.logoY )
color()
'''
payload = '''
local mouseJustPressed = love.mouse.isDown(1) and not lemontweaks.mouseWasDown
lemontweaks.mouseWasDown = love.mouse.isDown(1)

if mods.lemontweaks.config.customsounds.music.useCustomPlayer then
	if lemontweaks.menuPlaying == nil then
		lemontweaks.menuPlaying = true
	end

    local playerIconPadding = 5 + 16;

    local songArtist = lemontweaks.fetchedLevels[lemontweaks.current].artist:gsub("%b[]", "") or "unknown"
    local songName = lemontweaks.fetchedLevels[lemontweaks.current].name:gsub("%b[]", "") or "unknown"

	lemontweaks.menuX = lemontweaks.menuX or (lemontweaks.menuOpen and -(fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 11 + playerIconPadding * 4) or 0)

    if lemontweaks.moveMenu then
        lemontweaks.moveMenu = false

        if lemontweaks.menuOpen then
            flux.to(lemontweaks, 25, { menuX = 0 }):ease("outCubic")
        else
            flux.to(lemontweaks, 25, { menuX = -(fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 11 + playerIconPadding * 4) }):ease("outCubic")
        end
    end

    lemontweaks.helperOutlineRect(lemontweaks.menuX + 0, 26, fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 16 + playerIconPadding * 5, 30)

    color(1)
    love.graphics.setFont(fonts.digitalDiscoBold)

    lemontweaks.helperImgButton(sprites.player.shuffle, lemontweaks.menuX + 5 + playerIconPadding * 0, 33, function()
        lemontweaks.fetchedLevels = lemontweaks.shuffle(lemontweaks.fetchedLevels)
		lemontweaks.current = 1
		lemontweaks.tempDontAdvance = true

        cs.menuMusicManager:stop()
        cs.menuMusicManager:play()
    end, mouseJustPressed)

    local pauseIcon;

    if lemontweaks.menuPlaying then
        pauseIcon = sprites.player.pause
    else
        pauseIcon = sprites.player.play
        -- it's scuffed but it works
        cs.menuMusicManager:seek(lemontweaks.menuloopInfo.playhead)
    end

    lemontweaks.helperImgButton(pauseIcon, lemontweaks.menuX + 5 + playerIconPadding * 1, 33, function()
        lemontweaks.menuPlaying = not lemontweaks.menuPlaying

        if lemontweaks.menuPlaying then
            cs.menuMusicManager:seek(lemontweaks.menuloopInfo.playhead)
            cs.menuMusicManager:forceUnmute()
        else
            lemontweaks.menuloopInfo = cs.menuMusicManager:getInfo()
            cs.menuMusicManager:forceMute()
        end
    end, mouseJustPressed)
    lemontweaks.helperImgButton(sprites.player.back, lemontweaks.menuX + 5 + playerIconPadding * 2, 33, function()
        local currentSongInfo = cs.menuMusicManager:getInfo()

        if currentSongInfo.playhead - lemontweaks.fetchedLevels[lemontweaks.current].offset < 3 then
            lemontweaks.current = lemontweaks.current - 1
			lemontweaks.tempDontAdvance = true
        end

        cs.menuMusicManager:stop()
        cs.menuMusicManager:play()
    end, mouseJustPressed)
    love.graphics.print(songArtist .. ' - ' .. songName, lemontweaks.menuX + 5 + playerIconPadding * 3, 34)
    lemontweaks.helperImgButton(sprites.player.forward, lemontweaks.menuX + fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 10 + playerIconPadding * 3, 33, function()
        cs.menuMusicManager:stop()
        cs.menuMusicManager:play()
    end, mouseJustPressed)
    love.graphics.rectangle('fill', lemontweaks.menuX + fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 10 + playerIconPadding * 4, 26, 1, 30)
    lemontweaks.helperImgButton(sprites.player.menu, lemontweaks.menuX + fonts.digitalDiscoBold:getWidth(songArtist .. ' - ' .. songName) + 16 + playerIconPadding * 4, 33, function()
        lemontweaks.menuOpen = not lemontweaks.menuOpen
        lemontweaks.moveMenu = true
    end, mouseJustPressed)

    love.graphics.setFont(fonts.digitalDisco)
end
'''
position = "before"
target = "states/Menu.lua"
